<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

In this lab you will use Python (with the NumPy library) to carry out linear algebra operations.

1. Compute the scalar product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number.

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [3]:
import numpy as np

In [5]:
a = [-12, 16]
b = [12, 9]

In [9]:
#answer:
dot_product = np.dot(a,b)
print(dot_product)

0


2. Compute the Hadamard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [17]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [19]:
#answer:
h_product = a*b
print(h_product)

[[ 5 12]
 [21 32]]


In [ ]:
#desired output:
# np.array([[5,12],[21,32]])

3. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [23]:
# Add two matrices using a nested loop

X = [[1,2,3],
    [4,5,6],
    [7,8,9]]

Y = [[2,3,7],
    [1,4,9],
    [3,2,3]]

In [27]:
#answer:
rows = len(X) # Number of rows in the matrix
cols = len(X[0]) # Number of columns in the matrix

result = [[0 for _ in range(cols)] for _ in range(rows)] # Create 3 rows and 3 columns of 0 (3x3 Matrix)

# Iterate over rows
for i in range(rows):
    # Iterate over columns
    for j in range(cols):
        # Add the corresponding elements
        result[i][j] = X[i][j] + Y[i][j]
        
for row in result:
    print(row)

[3, 5, 10]
[5, 9, 15]
[10, 10, 12]


In [ ]:
#desired output:
#[[3,5,10],
# [5,9,15],
# [10,10,12]]

4. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [29]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[7, 2, 4],
    [3, 9, 5],
    [8, 1, 6]]

# 3x4 matrix
Y = [[5,8,2,6],
    [1,4,9,3],
    [7,2,5,8]]

#X is 3 x 3, #Y is 3 x 4 matrix
#result of XY is 3 x 4 matrix.

In [39]:
#answer:
rows_X = len(X) # number of rows in matrix X
cols_X = len(X[0]) # number of cols in matrix X

rows_Y = len(Y) # number of rows in matrix Y
cols_Y = len(Y[0]) # number of cols in matrix Y

# Check for compatibility (important for valid matrix multiplication)
if cols_X != rows_Y:
    print("Error: The number of columns in X must be equal to the number of rows in Y for matrix multiplication.")
else:
    # Initialize the result matrix with zeros
    # The result matrix will have dimensions (rows_X x cols_Y)
    result = [[0 for _ in range(cols_Y)] for _ in range(rows_X)]

    # Iterate over rows of X
    for i in range(rows_X):
        # Iterate over columns of Y
        for j in range(cols_Y):
            # Iterate over columns of X (or rows of Y)
            # This inner loop performs the dot product for each element of the result matrix
            for k in range(cols_X): # or range(rows_Y) - both are equivalent due to compatibility check
                result[i][j] += X[i][k] * Y[k][j]

    print("\nResult of Matrix Multiplication (X * Y):")
    for row in result:
        print(row)


Result of Matrix Multiplication (X * Y):
[65, 72, 52, 80]
[59, 70, 112, 85]
[83, 80, 55, 99]


In [ ]:
#desired output:
#[[65, 72, 52, 80],
# [59, 70, 112, 85],
# [83, 80, 55, 99]]

5. Compute the determinant of an n x n matrix.

Hint: Use
> np.linalg.det

In [43]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [69]:
#answer:
determinant = np.linalg.det(matrix)
print(f"Determinant of matrix: {determinant:.2f}")

Determinant of matrix: 18.00


6. Compute the inverse of an n x n matrix.

Hint: Use
> from numpy.linalg import inv

In [49]:
a = np.array([[1., 2.], [3., 4.]])

In [51]:
#answer:
from numpy.linalg import inv
inverse_mat = np.linalg.inv(a)
print(inverse_mat)

[[-2.   1. ]
 [ 1.5 -0.5]]


7. (Application)
Three customers made the following purchases of three different items at an office supply store:
* Customer W bought 2 notebooks, 4 pens and 3 staplers for \$38.80
* Customer X bought 3 notebooks, 3 pens and 2 staplers for \$32.00
* Customer Y bought 4 notebooks, 8 pens and 1 stapler for \$36.60

Based on this, how much did customer Z spend in buying 1 notebook, 2 pens and 4 staplers?

In [63]:
# answer
a= np.array([[2,4,3], [3,3,2], [4,8,1]])
p = np.array([38.8, 32,36.6])
unit_cost = np.linalg.solve(a,p)
n, p , s = unit_cost
print(f"Cost of one notebook (n): ${n:.2f}")
print(f"Cost of one pen (p): ${p:.2f}")
print(f"Cost of one stapler (s): ${s:.2f}")

Cost of one notebook (n): $3.30
Cost of one pen (p): $1.90
Cost of one stapler (s): $8.20


In [67]:
# Customer Z quantity
z = np.array([1,2,4])
# Total Spending of Customer Z 
z_spend = np.dot(z, unit_cost)
print(f"Total Spending from Customer Z: ${z_spend:.2f}")


Total Spending from Customer Z: $39.90




---



---



> > > > > > > > > © 2025 Institute of Data


---



---



