In [1]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [2]:
#question mark before or after the function
?print

In [3]:
?len

In [4]:
print?

In [5]:
# This is a single-line comment

In [6]:
'''
This is multi-line comment
THis is mutli-line comment
z=5+6
'''

'\nThis is multi-line comment\nTHis is mutli-line comment\nz=5+6\n'

In [7]:
"""
This is another multi-line comment
This is another multi-line comment
"""
# add a: after the code to prevent it from printing the comments

'\nThis is another multi-line comment\nThis is another multi-line comment\n'

In [8]:
user_name = 'Jason' #user_name is a string variable with 'Jason' stored as the value
user_id  = 2033 # user_id is an integer variable with 2033 stored as the value
paid_member = True #paid_member is boolean variable with True stored as the value

#two methods.
# assign a value to % and print
print ("current user name is: %s" % user_name)
print ("current user id is: %s" % user_id)
print ("current user is paid member: %s" % paid_member)

current user name is: Jason
current user id is: 2033
current user is paid member: True


In [9]:
#previous % is not neccessary, can just print directly
print ("current user name is: " , user_name) 
print ("current user id is: " , user_id) 
print ("current user is paid member: " , paid_member) 

current user name is:  Jason
current user id is:  2033
current user is paid member:  True


In [11]:
c = 3
print(c) # prints 3


#change c from 3 into 9
c = 9
print(c) # prints 9, note: the latest/updated value of c is printed 


#making a variable d has no impact on c
d = 12
print(d) # prints 12
print(c) # prints 9

3
9
12
9


In [12]:
#variables can be replaced with any other type of value (an integer can change into a string)
d = 'Jason'
print(d) # prints Jason

#variables can be used as values
e = c + 1
print(e) # prints 10

Jason
10


In [13]:
my_var = 20

In [14]:
# Integer: <int> is for whole numbers
# Float: <float>  is for decimal numbers
# String: <str> is for text aka string of characters
# Boolean: <bool> is either True or False.

a = 10
print( 'a is: ', type(a) )

b = 2.1
print( 'b is: ', type(b) )  

c = '2.1'
print( 'c is: ', type(c) ) # Note anything inside a quotation mark ('') will be regarded as string

d = 'bala'
print( 'd is: ', type(d) )

e = True
print('e is: ', type(e) )

a is:  <class 'int'>
b is:  <class 'float'>
c is:  <class 'str'>
d is:  <class 'str'>
e is:  <class 'bool'>


In [15]:
'''
32 = integer
3.14 = float
'32' = string
'''
# str -> int 
print ('From type ', type('32'),'changed to', type(int('32')))

# int -> str
print ('From type ', type(32), 'changed to ', type(str(32)))

#can you change from int and string to float?
# int / str -> float 
print (type(float(32)))
print (type(float('32')))

From type  <class 'str'> changed to <class 'int'>
From type  <class 'int'> changed to  <class 'str'>
<class 'float'>
<class 'float'>


In [16]:
# Operands: a,b
a = 10
b = 2

print(a+b) # 10+2
print(a-b) # 10-2
print(a*b) # 10*2
print(a/b) # 10/2
print(a%b) # remainder of 10/2
print(a**b) # 10^2

12
8
20
5.0
0
100


In [17]:
#see that if int is divided by float, it will automatically be changed to float.
print (5/2) # prints 2.5
print (int(5/2)) # prints 2
print (5/2.0) # prints 2.5
print (5.0/2) # prints 2.5 
print (5.0/2.0) # prints 2.5

2.5
2
2.5
2.5
2.5


In [18]:
# Need to import math module for math functions
import math

In [19]:
math.pi # The mathematical constant π = 3.141592..., to available precision.

3.141592653589793

In [22]:
# all values are returned in radians
x = 60
math.sin(x) # sine x
math.cos(x) # cosine x
math.tan(x) # tangent x

0.320040389379563

In [21]:
math.log(x) # returns the natural logarithm of x (to base e)
math.log(x,10) # returns the logarithm of x to the given base

y=3
math.pow(x,y) # returns x^y
math.sqrt(x) # returns square root of x

7.745966692414834

In [23]:
math.log(x) # returns the natural logarithm of x (to base e)


4.0943445622221

In [24]:
math.log(x,10) # returns the logarithm of x to the given base

1.7781512503836434

In [25]:
y=3
math.pow(x,y) # returns x^y

216000.0

In [26]:
math.sqrt(x) # returns square root of x

7.745966692414834

In [27]:
z=5.9
math.ceil(z) # return the ceiling of x as a float, the smallest integer value greater than or equal to x

6

In [28]:
math.floor(z) # return the floor of x as a float, the largest integer value less than or equal to x

5

In [29]:
# Python functions can be composed, meaning that you use one expression as part of another
import math
angle = 60
x = math.cos(angle + math.pi/2) 
y = math.exp(math.log(10.0)) 
print(x,y)

0.30481062110221835 10.000000000000002


In [30]:
# empty list
list0 = []

#numbers list
list1 = [1, 2, 3, 4, 5 ]

#mixed list
list2 = ['physics', 'chemistry', 1997, 2000]

# nested list, list within a list
list3 = ["mouse", [8, 4, 6], ['a']] #note in python, single or double quotes are both ok for string


In [31]:
my_list = ['p','r','o','b','e']
# Output: p
print(my_list[0]) #counting from left
print(my_list[-5]) #counting from right, starting from -1

# Output: o
print(my_list[2]) #counting from left
print(my_list[-3]) #counting from right

# Output: e
print(my_list[4]) #counting from left
print(my_list[-1]) #counting from right

p
p
o
o
e
e


In [32]:
company = [['John','manager',2011],['Jane','executive',2014]]
print(company[0][1])
print(company[1][2])

manager
2014


In [33]:
student = ['stu1', ['stu2', 28], 'stu3',['stu4','F',30]]
print(student[1][1])

28


In [34]:
my_list = ['a','b','c','d','e','f','g','h','i'] # there are 9 items in the list

# index 2 to (5-1)
print(my_list[2:5])

['c', 'd', 'e']


In [38]:
# index 0 to (count-5)
print(my_list[:-5])

['a', 'b', 'c', 'd']


In [36]:
# index 5 to last(count-1)
print(my_list[5:])

['f', 'g', 'h', 'i']


In [39]:
# index 0 to last(count-1)
print(my_list[:])

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']


In [40]:
print(my_list) #same output

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']


In [41]:
my_list = ['a','b','c','d','e','f','g','h','i'] 
my_list.append('j')
print(my_list)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [43]:
my_list = ['a','b','c','d','e','f','g','h','i']
# index 2 to (5-1)
del my_list[2:5]
print(my_list)

# index 5 to last(count-1)
del my_list[5:]
print(my_list)

# index 0 to last(count-1)
del my_list[:]
print (my_list)

['a', 'b', 'f', 'g', 'h', 'i']
['a', 'b', 'f', 'g', 'h']
[]


In [44]:
my_list = [123, 'clementi', 'x', 45]

# length of my_list
print (len(my_list))

# Insert 'y' at index 3
my_list.insert(3,'y')
print (my_list)

# Remove the first element in the list
my_list.pop(0)
print (my_list)

4
[123, 'clementi', 'x', 'y', 45]
['clementi', 'x', 'y', 45]


In [45]:
# len() returns the number of characters

fruit = 'durian'
print (len(fruit))

6


In [46]:
fruit = 'coconut' 
ingredient = ' oil' 
print (fruit + ingredient )
print('sing'*3) 

coconut oil
singsingsing


In [57]:
s = "cars don't fly" 
print (s[0:4] )

print (s[5:10]) 

print (s[11:] )

cars
don't
fly


In [56]:
# Use () to create tuples
tup1 = ('a', 'b', 6, 'example', 15)
# Access specific elements using [index]
print(tup1[1])

b


In [58]:
print(tup1[0:3]) # index range from 0 to 2, not this is a range, not until index 3 

('a', 'b', 6)


In [59]:
print(tup1[2:]) # index range from 2 to last index

(6, 'example', 15)


In [60]:
# Although it is impossible to update or change values in tuples, we can concatenate portions of different tuples.
tup2 = ('e', 'f')
tup3 = tup1 + tup2
print(tup3)

('a', 'b', 6, 'example', 15, 'e', 'f')


In [61]:
# deleting tuple using “del” statement
del tup3

In [62]:
# Empty dictionary
my_dict1 ={}

# Dictionary with integer keys
my_dict1 = {1: 'Apple', 2: 'Orange'}

# Dictionary with string keys
my_dict1 = {'Name': 'John', 'Age': 23, 'Class':'First'}
print(my_dict1)
print(type(my_dict1))

{'Name': 'John', 'Age': 23, 'Class': 'First'}
<class 'dict'>


In [63]:
# You may also create dictionary with dict() constructor
my_dict2 = dict([('Name','John'),('Age',23)])
print(my_dict2)
print(type(my_dict2))

{'Name': 'John', 'Age': 23}
<class 'dict'>


In [64]:
# Access values with keys
print(my_dict1['Name'])
print(my_dict1['Age'])

# Access values with get()
print(my_dict1.get('Name'))
print(my_dict1.get('Age'))

John
23
John
23


In [65]:
# key is not found
print(my_dict1.get('Address'))

None


In [66]:
# Access all keys
# return a list of keys in dictionary
mykeys = my_dict1.keys()
print(mykeys)

# Access all values
# Assign a variable to all the values, this variable becomes a list type 
my_values = my_dict1.values()
print(my_values)

dict_keys(['Name', 'Age', 'Class'])
dict_values(['John', 23, 'First'])


In [67]:
# Adding (key : value) pairs
new_dict = {'Name': 'John', 'Age':23, 'Class': 'First'}

# update values
new_dict['Name'] = 'Jane'

# Add new item
new_dict['Occupation'] = 'journalist'
new_dict['Phone_number'] = 123456789

print(new_dict)

{'Name': 'Jane', 'Age': 23, 'Class': 'First', 'Occupation': 'journalist', 'Phone_number': 123456789}


In [68]:
# Deleting (key : value) pair 
del new_dict['Phone_number']
print(new_dict)

{'Name': 'Jane', 'Age': 23, 'Class': 'First', 'Occupation': 'journalist'}


In [69]:
#delete and extract the value
print(new_dict.pop('Name'))
print(new_dict)

Jane
{'Age': 23, 'Class': 'First', 'Occupation': 'journalist'}


In [70]:
# return a list of keys in dictionary
print(new_dict.keys())

dict_keys(['Age', 'Class', 'Occupation'])


In [71]:
# return key-value pairs in the form of tuple
print(new_dict.items())

dict_items([('Age', 23), ('Class', 'First'), ('Occupation', 'journalist')])


In [72]:
# Keep copy of original 
copied_dict = new_dict.copy()
print (copied_dict)

{'Age': 23, 'Class': 'First', 'Occupation': 'journalist'}


In [73]:
# Once you've installed NumPy you can import it as a library:
import numpy as np

In [74]:
# Create a numeric array by directly converting a list or list of lists
my_list = [52, 37, 41, 32, 31]
my_list

[52, 37, 41, 32, 31]

In [75]:
a = np.array(my_list) # create 1-D array
print((type(a),a.shape,a[0],a[1],a[2]))

(<class 'numpy.ndarray'>, (5,), 52, 37, 41)


In [76]:
#We can initialize numpy arrays from nested Python lists, and access elements using square brackets:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] #list
b = np.array(my_matrix) # create 2-D array
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
b[1][2]

6

In [78]:
b.shape # returns the tuple of array dimensions

(3, 3)

In [79]:
np.arange(0,10) #create 1-D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.zeros(3) # create 1-D array of all zeros

array([0., 0., 0.])

In [81]:
np.zeros((5,5)) # create 2-D array of all zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.ones(3) # create 1-D array of all ones

array([1., 1., 1.])

In [83]:
np.ones((3,3)) # create 2-D array of all ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
#start from 0, end with 10, with 3 numbers
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [85]:
#start from 0, end with 10, with 50 numbers
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [86]:
np.eye(4) # create a 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
np.random.rand(2) #creae an array filled with random values

array([0.77768352, 0.81090297])

In [88]:
np.random.randn(2)

array([0.1175658 , 0.09230506])

In [89]:
np.random.randn(5,5)

array([[ 1.42212949, -0.91306977, -0.36076264,  0.12771799,  1.13693452],
       [ 0.7421735 ,  0.95251978,  0.17655988,  0.85524096, -0.51529769],
       [ 1.92232065, -0.83257235, -0.1852984 ,  0.39999188, -1.8719708 ],
       [ 1.21817526, -1.40558191,  1.00981549, -0.04425941, -1.17945542],
       [ 0.30945107, -0.71778854,  0.89929588, -0.44018688,  1.67380784]])

In [90]:
np.random.randint(1,100)

54

In [91]:
np.random.randint(1,50,20)

array([43,  1, 14, 34, 28, 48, 20, 10,  6,  2,  9, 28, 27, 25, 44, 27, 40,
       13, 19, 11])

**Array Indexing (Accessing elements)**
**Slicing:** Similar to Python lists, numpy arrays can be slices. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

For the 2-D array:
 *  **Note** That the second index (after the colon) is **not** included in the range. 
 *  For example, if you say [0:2] that mean 0 and 1 ... if you say [2:5] that means 2,3,4. 
 * variable_name=array_name[row_index1:row_index2,column_index1:column_index2]


In [92]:
x1 = np.array([5,0,3,3,7,9])
x1[0]

5

In [93]:
x1[5]

9

In [94]:
# Use list for mixed data types
x2 = np.array([[3,5,2,4],[7,6, 8,8],[1,6,7,7]],dtype=np.int)
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [95]:
x2[0,0]

3

In [96]:
#One-dimensional subarrays
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [97]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [98]:
x2 = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [99]:
x2[:,0] # first column of x2

array([12,  7,  1])

In [100]:
x2[0,:] # first row of x2

array([12,  5,  2,  4])

In [101]:
x2[0] # equivalent to x2[0,:]

array([12,  5,  2,  4])

In [102]:
w = np.array([1, 2])  # Let numpy choose the datatype
x = np.array([1.0, 2.0])  # Let numpy choose the datatype
y = np.array([1, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(w.dtype, x.dtype, y.dtype, z.dtype)

int32 float64 float64 int64


In [103]:
# Create a numeric vector to store workshop marks
Marks = np.array([52, 37, 41, 32, 31], float)
MarksAdj = Marks + 20 # Operations on 'Marks' and store it on 'MarksAdj'
MarksAdj

array([72., 57., 61., 52., 51.])

In [104]:
a = np.array([[1,2],[3,4]], float)
b = np.array([[2,0],[1,3]],float)
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [105]:
x = np.array([[1,2],
              [3,4]])

print (np.sum(x))  # Compute sum of all elements; prints "10"
print (np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print (np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [113]:
import numpy as np
import pandas as pd

In [114]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [115]:
# using lists
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [116]:
# Numpy arrays
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [117]:
# dictionary
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [118]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])   

In [119]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [120]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan']) 

In [121]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [122]:
ser1['USA']

1

In [123]:
# Operations are then also done based off of index:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [124]:
# Create the vectors
month = ['Feb','Mar','Apr','May','Jun','Jul']
record = ['read','est','read','est','read','est']
electricity = [47.0,49.0,70.0,np.nan,78,71]
water = [18.0,17.0,14.0,np.nan,15.0,14.0]
gas = [21,21,24,np.nan,27,19]

In [125]:
# To merge lists together we will use the zip function
PUBdataset = list(zip(month,record,electricity,water,gas))
PUBdataset

[('Feb', 'read', 47.0, 18.0, 21),
 ('Mar', 'est', 49.0, 17.0, 21),
 ('Apr', 'read', 70.0, 14.0, 24),
 ('May', 'est', nan, nan, nan),
 ('Jun', 'read', 78, 15.0, 27),
 ('Jul', 'est', 71, 14.0, 19)]

In [126]:
# PUB will be a DataFrame object.
# You can think of this object holding the contents of the PUBdataset in a format similar to a sql table or an excel spreadsheet.
# Lets take a look below at the contents inside PUB.
PUB = pd.DataFrame(data=PUBdataset, columns=['month','record','electricity','water','gas'])
PUB

month record  electricity  water   gas
0   Feb   read         47.0   18.0  21.0
1   Mar    est         49.0   17.0  21.0
2   Apr   read         70.0   14.0  24.0
3   May    est          NaN    NaN   NaN
4   Jun   read         78.0   15.0  27.0
5   Jul    est         71.0   14.0  19.0

In [127]:
# Access elements(rows)
PUB[1:3]

month record  electricity  water   gas
1   Mar    est         49.0   17.0  21.0
2   Apr   read         70.0   14.0  24.0

In [128]:
PUB[4:5]

month record  electricity  water   gas
4   Jun   read         78.0   15.0  27.0

In [130]:
# Access elements(columns)
PUB['record']

0    read
1     est
2    read
3     est
4    read
5     est
Name: record, dtype: object

In [131]:
PUB.record

0    read
1     est
2    read
3     est
4    read
5     est
Name: record, dtype: object

In [132]:
PUB[['electricity','water']]

electricity  water
0         47.0   18.0
1         49.0   17.0
2         70.0   14.0
3          NaN    NaN
4         78.0   15.0
5         71.0   14.0

In [133]:
PUB.electricity[1]

49.0

In [134]:
PUB['electricity'][1]

49.0

In [135]:
PUB

month record  electricity  water   gas
0   Feb   read         47.0   18.0  21.0
1   Mar    est         49.0   17.0  21.0
2   Apr   read         70.0   14.0  24.0
3   May    est          NaN    NaN   NaN
4   Jun   read         78.0   15.0  27.0
5   Jul    est         71.0   14.0  19.0

In [136]:
PUB.dropna()

month record  electricity  water   gas
0   Feb   read         47.0   18.0  21.0
1   Mar    est         49.0   17.0  21.0
2   Apr   read         70.0   14.0  24.0
4   Jun   read         78.0   15.0  27.0
5   Jul    est         71.0   14.0  19.0

In [137]:
PUB.dropna(axis=0) # drop rows with na values

month record  electricity  water   gas
0   Feb   read         47.0   18.0  21.0
1   Mar    est         49.0   17.0  21.0
2   Apr   read         70.0   14.0  24.0
4   Jun   read         78.0   15.0  27.0
5   Jul    est         71.0   14.0  19.0

In [138]:
PUB.dropna(axis=1) # drop columns with na values

month record
0   Feb   read
1   Mar    est
2   Apr   read
3   May    est
4   Jun   read
5   Jul    est

In [139]:
PUB.gas.mean()

22.4

In [140]:
PUB_NoNA=PUB.dropna()

In [141]:
PUB_NoNA

month record  electricity  water   gas
0   Feb   read         47.0   18.0  21.0
1   Mar    est         49.0   17.0  21.0
2   Apr   read         70.0   14.0  24.0
4   Jun   read         78.0   15.0  27.0
5   Jul    est         71.0   14.0  19.0

In [142]:
#Add the price of electricity, water and gas into a total
total = []
total = PUB['electricity']+PUB['gas']+PUB['water']
PUB['total']=total

In [143]:
PUB

month record  electricity  water   gas  total
0   Feb   read         47.0   18.0  21.0   86.0
1   Mar    est         49.0   17.0  21.0   87.0
2   Apr   read         70.0   14.0  24.0  108.0
3   May    est          NaN    NaN   NaN    NaN
4   Jun   read         78.0   15.0  27.0  120.0
5   Jul    est         71.0   14.0  19.0  104.0

In [144]:
#Focus on the months where readings were actually taken
#Want to look at only electricity
#Create a subset for that
electricity_read = PUB[PUB.record == 'read'].electricity

In [145]:
electricity_read

0    47.0
2    70.0
4    78.0
Name: electricity, dtype: float64

In [146]:
from pandas import DataFrame, read_csv

In [147]:
PUB

month record  electricity  water   gas  total
0   Feb   read         47.0   18.0  21.0   86.0
1   Mar    est         49.0   17.0  21.0   87.0
2   Apr   read         70.0   14.0  24.0  108.0
3   May    est          NaN    NaN   NaN    NaN
4   Jun   read         78.0   15.0  27.0  120.0
5   Jul    est         71.0   14.0  19.0  104.0

In [148]:
PUB.to_csv('PUB.csv',index = False, header = True)

In [149]:
nPUB = pd.read_csv('PUB.csv')

In [150]:
nPUB

month record  electricity  water   gas  total
0   Feb   read         47.0   18.0  21.0   86.0
1   Mar    est         49.0   17.0  21.0   87.0
2   Apr   read         70.0   14.0  24.0  108.0
3   May    est          NaN    NaN   NaN    NaN
4   Jun   read         78.0   15.0  27.0  120.0
5   Jul    est         71.0   14.0  19.0  104.0

In [151]:
# Delete the csv file after we are done using it

In [152]:
import os
os.remove('PUB.csv')